name: Publish to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read      # allow checkout
  pages: write        # allow deployment
  id-token: write     # verify provenance

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4       # optional, but keeps things current

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Build site
        run: bundle exec jekyll build --source docs --destination site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3   # ← upgraded
        with:
          path: ./site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4            # ← upgraded
